---
format: html
editor: visual
bibliography: references.bib
---

### Sample Collection

We leveraged eDNA samples collected on the 2019 US-Canada Integrated Ecosystems and Acoustics-Trawl Survey for Pacific hake from 2 July to 19 August 2019. The study area is encompassed by the California Current System, which is 500-800km wide, extends from 43°N to 23°N, and comprises an equatorward surface current and a subsurface poleward current that is concentrated mainly on the continental shelf [@hickey79]. The system is characterized by strong alongshore advection, inshore upwelling concentrated primarily along the continental shelf break, and multiple terrestrial and oceanic water sources [e.g. @mcclatchie14, @auad_etal11]. These complex oceanographic processes support a highly productive and diverse assemblage of plankton and fishes, form a rich prey base for at least 25 cetacean species that inhabit the study area [@carretta_etal23].

A full description of field sampling and DNA extraction are provided in Shelton et al. (2022). Briefly summarized, we use water samples that were previously collected seawater at 175 stations in the study area, spanning south-north from latitudes 37.89499°N to 48.39881°N and west-east 126.4298°W to 122.8638°W. We targeted six depths, so that our sample set of 516 samples included 148 samples collected at 0 m, 147 samples collected at 50 m, 74 samples collected at 150 m, 73 samples collected at 300 m, and 74 samples collected at 500 m. The field team collected samples using niskin bottles attached to a CTD rosette and filtered 2.5 L of water using a 47-mm diameter mixed cellulose ester (MCE) filter with a 1-µm pore size and a vacuum filtration manifold connected to a vacuum pump, then immediately preserved the filters in Longmire's buffer and stored them at room temperature until extraction.

### Sample Processing

DNA was previously extracted using a phase-lock phenol chloroform method as described in Ramón-Laca et al. (2021). Using this extracted DNA, we randomized stations and depths across 96-well working plates, removed one plate at a time for PCR amplification and library preparation, and stored samples in a -20 C freezer when not in use. Each time we removed a plate from the freezer, we recorded a freeze/thaw cycle for that plate in order to examine the effect of expected DNA degradation due to freeze/thaw cycles on downstream probability of detecting rare species.

Next, we tested all samples for inhibition by spiking an internal positive control (IPC) of known concentration into each sample and quantifying it using a probe assay with quantitative PCR (qPCR), and identified inhibited samples by examining the IPC concentration, as described in Shelton et al. (2022). For each sample, we selected a dilution that was determined from the qPCR data (described above) to be not inhibited, which was either 1x or 0.2x across all samples.

We then amplified each sample with three different primer sets: MFU targeting fishes using the 12S region [@miya_etal15], MV1 targeting vertebrates using the 12S region, [@valsecchi_etal20] and DL targeting only cetaceans using the control region [@baker_etal06]. For all samples, we ran one technical PCR replicate for MFU, one for DL, and three for MV1. We optimized primer, Taq, and cycling conditions based using mock communities [-@shaffer_etal25].

Our reaction mixture for amplification (PCR1) consisted of 10 μL of Phusion Master Mix (2X), 0.4 μL of the forward primer (10 μM); 0.4 μL of the reverse primer (10 μM), 0.6 μL of 100% DMSO, 0.5 μL of rAlbumin (20 μg/μL), 4.4 μL of nuclease-free water and 2 μL of DNA template. We ran PCR1 with the following cycling conditions: an initial denaturation of 98°C for 30 sec; followed by cycles of: denaturation (98°C for 10 sec), annealing (60°C for 30 sec), and extension (72°C for 3 sec); with a final extension of 72°C for 10 min and hold at 4°C. We ran 35 cycles for MFU and MV1, and 40 cycles for DL.

If a sample failed to produce a band at the previously determined optimal dilution when amplified using MV1 or MFU, we diluted the sample and reran it until a visible band was produced. We could not do the same for DL, which targets only cetaceans, because the rarity of our target made it prohibitively difficult to distinguish between an inhibited sample and a negative sample. Here we assumed that the optimal dilution selected by qPCR was not inhibited and treated samples without bands as negative detections.

Any MFU and MV1 samples that returned fewer than 100 total reads after sequencing were rerun in an effort to complete the dataset to include one successful MFU replicate and three successful MV1 replicates. This required up to six replicate sequencing runs in some cases.

### Library Preparation and Sequencing

We then cleaned the amplified PCR product using Ampure Beads (1.2x beads:product ratio, with two 70% ethanol washes) and then indexed each sample in a second PCR reaction (PCR2) using the following reaction mixture: 12.5 μL of KAPA HiFi HotStart ReadyMix (Roche Diagnostics), 1.25 μL of IDT for Illumina DNA/RNA UD Indexes (Sets A-D), as well as primer-specific volumes of PCR1 product and nuclease free water. We added 5 μL PCR1 product, and 6.25 μL of nuclease free water for all MFU and MV1 samples, and added 11.25 μL PCR1 product and no nuclease free water to all DL samples. We ran PCR2 using the following cycling conditions: an initial denaturation of 95°C for 5 min; cycles of: 98°C for 20 sec, 56°C for 30 sec, 72°C for 1 min; and a final extension of 72°C for 5 min. We ran **35 \[IS THIS RIGHT?\]** cycles for MiFish-U and MarVer1, and 12 cycles for D-loop.

After indexing, we visualized the PCR product on a 2% agarose gel and quantified DNA concentration using Quant-iT™ dsDNA Assay Kit (Thermo Fisher Scientific, USA) with Fluoroskan™ Microplate Fluorometer (Thermo Fisher Scientific, USA). We then normalized all indexed products to a concentration of **5ng/ul \[IS THIS RIGHT?\]**, pooled the normalized product into 96-sample libraries for sequencing, and then extracted the target band using the E-Gel™ SizeSelect™ II Agarose Gels (Thermo Fisher Scientific, USA). Finally, we loaded our pooled libraries, in 6-8 pM concentrations with a 20% PhiX spike-in, onto an Illumina MiSeq platform at the University of Washington with a v3 600 cycle kit. In total, we ran 36 sequencing runs from May 2023 to July 2025.

For every sequencing run, we added a sample with nuclease-free water (negative control) and genomic DNA from kangaroo (positive control) to PCR1 and carried it through the rest of the library preparation workflow. If anything other than human or NA was found in the negative control, or if kangaroo appeared in any other eDNA sample, we omitted that plate from the final analysis. This occurred for only one plate **of technical replicates, which was later re-run without contamination \[IS THIS RIGHT?\]**.

### Bioinformatic Processing

We analyzed all sequencing data using the bioinformatics workflow established in Guri et al. (2025). We trimmed Illumina-demultiplexed reads with Cutadapt v4.9 to remove primer and adapter sequences, allowing a maximum mismatch rate of 0.1 (Martin, 2011). We then conducted quality filtering and minimum-length truncation using DADA2, and inferred amplicon sequence variants (ASVs) using default denoising settings [@Callahan2016].

Following initial QAQC of the raw sequence data, we queried each unique ASV against a vertebrate mitochondrial subset of the January 2025 NCBI nr eukaryote database using standalone BLAST configured with “-word_size 20 -evalue 1e-30 -max_target_seqs 100” (Altschul et al., 1990), supplemented with a negative-taxid file to remove taxa with distributions outside the North Pacific Ocean. We made taxonomic assignments using a least-common-ancestor procedure in TaxonKit v0.17 (Shen & Ren, 2021), prioritizing exact-identity matches and otherwise applying a stepwise identity threshold (\>99.3%, \>98%). We manually reviewed all marine mammal identifications to ensure consistency with regional species distributions.

### Detection Data QAQC

After bioinformatic processing of all samples, we removed any additional dilutions of MFU or MV1 samples that were run to maximize sequencing success, keeping only the iteration with the greatest total read count. We then defined a sample as a station/depth/technical replicate combination. To obtain positive detections for each sample, we kept any species with \> 1 sequencing read. We filtered out any non-target (non-cetacean) species, and also removed detections of bottlenose dolphins, considered likely contamination, and unidentified Balaenopterids or Delphinids. Across all samples, we define non-detection as 0 reads for a given cetacean species in a station/depth location that was positive for non-target species (e.g. fish) in either MFU or MV1 sequence data.

### Data Analysis

#### How does observation bias affect rare DNA detectability?

Because various decisions made during sample collection, processing, and sequencing can introduce observation bias, we first leveraged the information contained in multiple technical replicates from individual biological samples to better understand the occupancy, capture, and detection processes for cetacean eDNA. Here we examine the probability of detecting cetacean DNA from any species, under the assumption that all cetacean DNA is equally capable of being detected if it is present \[cite Shaffer paper here?\]. We used a Bayesian hierarchical occupancy model to separately estimate the probability of occupancy/capture by depth and detectability by primer, based on the model used in Patin et al. (submitted).

We modeled the presence of cetacean eDNA in a given biological replicate at site $s$ and depth $d$, $z_{s,d}$, as a Bernoulli random variable with occurrence probability $\Psi_d$:

$$ z_{s,d} \sim \text{Bernoulli}(\Psi_{d}) $$

where probability of presence in a sample at depth $\Psi_d$ is a smooth, species-specific function of sample depth $D_d$:

$$ \text{logit}(\Psi_d) = s(d) \cdot D_d. $$

Each biological replicate was then subsampled for PCR amplification with three different primer sets. We modeled the observed detection of cetacean eDNA in each technical replicate $x_t$ as a Bernoulli random variable with primer-specific detection probability $\Omega_\text{primer}$ conditional on presence in the biological sample $z_{s,d}$:

$$ x_t \sim \text{Bernoulli}({\Omega_\text{primer}} \cdot z_{s,d}). $$

Using the results of this model, we simulated the primer-specific expected probability of detection with increasing technical replication.

Finally, we examined the effect of freeze/thaw cycles on probability of detection (POD) across all species using a generalized linear model (GLM) with a single interaction term between the number of freeze/thaw cycles and primer, using a binomial distribution, and generated 95% confidence intervals by bootstrapping the dataset 10,000 times and extracting the 2.5% and 97.5% quantiles of the model slope. We then determined that the relationship between the number of freeze/thaw cycles and POD for each primer is significant if 95% confidence interval does not cross zero. Following this, we calculate the predicted POD between one and seven freeze/thaw cycles for each primer as POD = Intercept + Slope\*Thaw, using mean bootstrap values to calculate the mean expectation, and 2.5% and 97.5% bootstrap values to calculate the upper and lower bounds of the 95% CI.

#### Question 1: Does species-specific POD vary with depth?

To determine whether species-specific POD varies in the z dimension, we used generalized additive models [GAMs; @Wood2017] implemented using the mgcv package in R [@RCoreTeam2016]. GAMs have previously been demonstrated to be an appropriate tool for modeling spatial use in cetaceans (e.g. @Becker2016; @Becker2019; @Becker2020; @becker_etal22; @abrahms_etal19b). We fit all GAMs using species-specific 0/1 detections as the response variable with a binomial distribution and logit link function, and estimated model parameters using REML. Models examining depth effect alone were built iteratively, starting with (1) assessing probability of detection (POD) across all species at sampling depths between 1 and 500m, then (2) allowing y-intercept to vary by species, and finally (3) allowing model smooth to vary by species. Although we have determined that primer specificity and technical replication affect POD in our samples, we have excluded these from downstream modeling since primers and technical replication were applied consistently across samples. **Should we add Thaw??**

In addition to examining depth variability across species-level strata, we examined several other ecological stratification schemes in order to determine whether depth variability in detection probability is driven by (1) evolutionary inertia (i.e. taxonomic family) or (2) preferred prey type. We assessed model fit using AIC, and model performance using standard metrics including the percent of deviance explained, the area under the receiver operating characteristic curve [AUC, @fawcett06], the true skill statistic [TSS, @allouche_etal06], and a visual comparison of predicted vs. observed detection rates across sampling depths. We also visually compared our model-based predictions of probability of detection across depth with estimates of species-specific time-at-depth as reported in [@watwood_buonantony12] and [@u_s_departmentofthenavy17].

#### Question 3: Does depth variability in POD covary with xy variability?

We returned to the use of GAMs in a frequentist context to address Question 3, and again built iterative models in order to examine covariability between depth, latitude, and longitude on a per-species basis. We began by examining whether xy variability explained a significant amount of remaining variability left in the model after depth variability was account for (i.e. POD \~ z + xy), then tested whether x, y, and z covary (i.e. POD \~ xyz). Finally, we allowed the model of xyz covariability to vary idependently by species.

We assessed model fit using AIC, and model performance using percent deviance explained, AUC, and TSS, as in Question 1. We then conducted a visual comparison of the predicted depth of maximum POD across and our observed detection depth within the study area for the most frequently observed baleen whale, dolphin, and beaked whale.
